### ISSUE TITLE
客户端怎么引入weex

### ISSUE THREAD

**Issue by lixingdecai** [cyforever123/weex-hongkong#1]
感谢你的分享。还有一个疑问，weex的.we或者.vue文件是在哪里生产bundle.js文件，怎么引入的android的工程当中。平常要怎么维护，可以实现热加载么

**Comment by cyforever123** [comment]
怎么引入的android的工程当中:
答：见这篇博客http://blog.csdn.net/dfskhgalshgkajghljgh/article/details/52757849 当然工程里面也有android原生代码，可以参考。

weex的.we或者.vue文件是在哪里生产bundle.js文件:
答：我目前用的0.8的版本，不是基于vue，直接在webstorm里面输入weex test.we 编译的，具体图文示例如下：http://blog.csdn.net/dfskhgalshgkajghljgh/article/details/54732559

平常要怎么维护，可以实现热加载么？
答：是实现热更新的，weex底层有websocket长连接，会实时刷新。或者不用websocket，因为每次都去请求js，你把js换掉，自然就更新了，只是没有那么实时，需要下一次请求。 其实你后台如果配置图片的时候，也是希望配置完，下次请求图片url的时候，变化，原理是一样的。

**Comment by lixingdecai** [comment]
非常感谢
